<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/style.css">
    <title>Дитячі садки "Діти сонця"</title>
</head>

<body>
<div class="container">
    <header>
        <a href="/">
            <img src="https://www.factinate.com/storage/app/media/factinate/2021/05/Michi-no-miya_Hirohito_1902.jpg"
                 alt="Логотип">
        </a>
        <nav>
            <ul>
                <li><a href="/">Наші групи</a></li>
                <li><a href="faq.ftlh">FAQ</a></li>
                <li><a href="info.ftlh">Про нас</a></li>
            </ul>
        </nav>
    </header>

    <div class="main">

        <section id="slider" class="slider">
            <h3>Дитячий сад "Діти сонця"</h3>
            <div class="system">
                <div class="sun"></div>
                <div class="orbit earth">
                    <div class="globe earth">
                        <div class="orbit moon">
                            <div class="globe moon"></div>
                        </div>
                    </div>
                </div>
            </div>
            <p>Ласкаво просимо до нашого дитячого саду! Ми пропонуємо якісну та зрілу освіту для вашого малятка.
                Наші вихователі з любов'ю дбають про кожного малюка, створюючи теплу та безпечну атмосферу для
                розвитку.</p>
        </section>

        <section id="news" class="news">
            <h3>Останні новини</h3>
            <p>Спостерігайте за нашими останніми новинами та подіями в нашому дитячому саду. Ми постійно
                розвиваємося та впроваджуємо нові цікаві програми для дітей.</p>
        </section>

        <section id="about" class="about">
            <h3>Наші клієнти</h3>
            <p>Дякуємо всім нашим клієнтам за довіру! Ми працюємо для того, щоб забезпечити найкращі
                умови для навчання та розвитку вашого дитинства.</p>
        </section>

    </div>

    <footer>
        <div class="contact-icons">
            <a href="tel:+380676110670" target="_blank"><i class="fa-solid fa-phone"></i>Телефон</a>
            <a href="mailto:kiryuchan2004@gmail.com" target="_blank"><i class="fa-solid fa-envelope"></i>Email</a>
            <a href="https://t.me/Kiryuchan1" target="_blank"><i class="fab fa-telegram"></i>Телеграм</a>
            <a href="https://api.whatsapp.com/send?phone=номер-телефону" target="_blank"><i
                        class="fab fa-whatsapp-square"></i> WhatsApp</a>
        </div>
    </footer>
</div>
</body>
</html>
